/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coyote.profile;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

public class ProfileServiceConstructor {
    @Test
    public void testConstructor() {
        ProfileService classUnderTest = new ProfileService();
        assertNotNull(classUnderTest, "should have reference");
    }
}
